// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.Interfaces;
namespace var
{

}

[TestFixture]
public class QautoTest
{
    string firstname = "Nick";
    string lastname = "Nuck";
    string password = "Pass12345";
    string email = "77test@test.com";
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void Test1FullTest()
    {
        //Test SignUp user
        driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto.forstudy.space/");
        driver.Manage().Window.Size = new System.Drawing.Size(1900, 1000);
        Thread.Sleep(2000);
        driver.FindElement(By.CssSelector(".hero-descriptor_btn")).Click();
        driver.FindElement(By.Id("signupName")).Click();
        driver.FindElement(By.Id("signupName")).SendKeys(firstname);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("signupLastName")).Click();
        driver.FindElement(By.Id("signupLastName")).SendKeys(lastname);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("signupEmail")).Click();
        driver.FindElement(By.Id("signupEmail")).SendKeys(email);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("signupPassword")).Click();
        driver.FindElement(By.Id("signupPassword")).SendKeys(password);
        Thread.Sleep(1000);
        driver.FindElement(By.Id("signupRepeatPassword")).Click();
        driver.FindElement(By.Id("signupRepeatPassword")).SendKeys(password);
        Thread.Sleep(3000);
        driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
        WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(100));
        wait.Until(driver => driver.FindElements(By.XPath("//*[@id=\'userNavDropdown\']")).Count > 0);
        var elements = driver.FindElements(By.XPath("//*[@id=\'userNavDropdown\']"));
        Assert.True(elements.Count > 0);
        //Test check Name and Lastname in Profile
        driver.FindElement(By.LinkText("Profile")).Click();
        Thread.Sleep(3000);
        //Test Add Car
        driver.FindElement(By.LinkText("Garage")).Click();
        Thread.Sleep(3000);
        //WebDriverWait wait1 = new WebDriverWait(driver, TimeSpan.FromSeconds(100));
        wait.Until(driver => driver.FindElement(By.XPath("//button[text()='Add car']"))).Click();
        Thread.Sleep(1000);
        wait.Until(driver => driver.FindElement(By.Id("addCarBrand"))).Click();
        wait.Until(driver => driver.FindElement(By.XPath("//option[text()='BMW']"))).Click();
        wait.Until(driver => driver.FindElement(By.XPath("//option[. = 'X5']"))).Click();
        driver.FindElement(By.Id("addCarMileage")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("addCarMileage")).SendKeys("200");
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
        Thread.Sleep(3000);
        //Test add expenses
        driver.FindElement(By.CssSelector(".car_add-expense")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("addExpenseMileage")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("addExpenseMileage")).Clear();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("addExpenseMileage")).SendKeys("250");
        Thread.Sleep(1000);
        driver.FindElement(By.Id("addExpenseLiters")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("addExpenseLiters")).SendKeys("100");
        Thread.Sleep(1000);
        driver.FindElement(By.Id("addExpenseTotalCost")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.Id("addExpenseTotalCost")).SendKeys("50");
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
        Thread.Sleep(3000);
        //test delete User
        driver.FindElement(By.LinkText("Settings")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".btn-danger-bg")).Click();
        Thread.Sleep(1000);
        driver.FindElement(By.CssSelector(".btn-danger")).Click();
        Thread.Sleep(3000);
    }


    //[Test]
    //public void Test2deleteUser()
    //{
    //    driver.Navigate().GoToUrl("https://guest:welcome2qauto@qauto.forstudy.space/");
     //   driver.Manage().Window.Size = new System.Drawing.Size(1900, 1000);
        //Thread.Sleep(2000);
     //   driver.FindElement(By.CssSelector(".btn-outline-white")).Click();
        //Thread.Sleep(1000);
     //   driver.FindElement(By.Id("signinEmail")).Click();
       // driver.FindElement(By.Id("signinEmail")).SendKeys(email);
        //Thread.Sleep(1000);
        //driver.FindElement(By.Id("signinPassword")).Click();
        //driver.FindElement(By.Id("signinPassword")).SendKeys(password);
        //Thread.Sleep(1000);
        //driver.FindElement(By.CssSelector(".btn-primary:nth-child(2)")).Click();
        //{
         //   WebDriverWait wait = new WebDriverWait(driver, System.TimeSpan.FromSeconds(100));
         //   wait.Until(driver => driver.FindElements(By.XPath("//*[@id=\'userNavDropdown\']")).Count > 0);
       // }
        //var elements = driver.FindElements(By.XPath("//*[@id=\'userNavDropdown\']"));
        //Assert.True(elements.Count > 0);
        //driver.FindElement(By.LinkText("Settings")).Click();
        //Thread.Sleep(1000);
        //driver.FindElement(By.CssSelector(".btn-danger-bg")).Click();
        //Thread.Sleep(3000);
        //driver.FindElement(By.CssSelector(".btn-danger")).Click();
    //}


}
